id = "brave-search"
name = "Brave Search"
description = "Model Context Server for Brave Search"
version = "0.0.1"
schema_version = 1
authors = ["anon <anon@example.com>"]
repository = "https://github.com/kevinehosford/brave-search"

[context_servers.brave-search]
name = "Brave Search"
